# Generated by Django 5.1.15 on 2026-05-30 12:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("habit.created", "Habit Created"),
                            ("habit.completed", "Habit Completed"),
                            ("habit.streak", "Streak Milestone"),
                            ("habit.deleted", "Habit Deleted"),
                            ("user.login", "User Login"),
                            ("user.registered", "User Registered"),
                            ("challenge.joined", "Challenge Joined"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("payload", models.JSONField(default=dict)),
                (
                    "ts",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-ts"],
                "indexes": [
                    models.Index(
                        fields=["user", "ts"], name="analytics_a_user_id_3e5e69_idx"
                    ),
                    models.Index(
                        fields=["user", "event_type"],
                        name="analytics_a_user_id_7df679_idx",
                    ),
                    models.Index(fields=["ts"], name="analytics_a_ts_3ee833_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserInsight",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "insight_type",
                    models.CharField(
                        choices=[
                            ("peak_time", "Peak Completion Time"),
                            ("streak_risk", "Streak at Risk"),
                            ("recommendation", "Habit Recommendation"),
                            ("weekly_summary", "Weekly Summary"),
                            ("milestone", "Milestone Reached"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                (
                    "generated_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insights",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-generated_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read"],
                        name="analytics_u_user_id_748732_idx",
                    ),
                    models.Index(
                        fields=["user", "generated_at"],
                        name="analytics_u_user_id_798f1b_idx",
                    ),
                ],
            },
        ),
    ]
