# Generated by Django 5.1.15 on 2026-05-31 04:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupChallenge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, max_length=1000)),
                ("habit_type", models.CharField(default="BINARY", max_length=20)),
                (
                    "target_value",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                ("target_unit", models.CharField(blank=True, max_length=30)),
                (
                    "privacy",
                    models.CharField(
                        choices=[
                            ("PUBLIC", "Public — anyone can join"),
                            ("INVITE", "Invite only"),
                            ("PRIVATE", "Private — hidden from search"),
                        ],
                        default="PUBLIC",
                        max_length=10,
                    ),
                ),
                ("max_participants", models.PositiveSmallIntegerField(default=50)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("invite_code", models.CharField(blank=True, max_length=10, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_challenges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChallengeParticipant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("score", models.PositiveIntegerField(default=0)),
                ("completions", models.PositiveIntegerField(default=0)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("last_active", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="challenge_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="social.groupchallenge",
                    ),
                ),
            ],
            options={
                "ordering": ["-score"],
            },
        ),
        migrations.CreateModel(
            name="SocialFeedItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("HABIT_COMPLETED", "Habit Completed"),
                            ("STREAK_REACHED", "Streak Milestone"),
                            ("CHALLENGE_JOINED", "Joined Challenge"),
                            ("CHALLENGE_WON", "Won Challenge"),
                            ("BADGE_EARNED", "Badge Earned"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField(blank=True)),
                ("payload", models.JSONField(default=dict)),
                ("is_public", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Friendship",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("DECLINED", "Declined"),
                            ("BLOCKED", "Blocked"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "addressee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_friend_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_friend_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["requester", "status"], name="social_frie_request_877cc3_idx"
                    ),
                    models.Index(
                        fields=["addressee", "status"], name="social_frie_address_a01a66_idx"
                    ),
                ],
                "unique_together": {("requester", "addressee")},
            },
        ),
        migrations.AddIndex(
            model_name="groupchallenge",
            index=models.Index(
                fields=["is_active", "privacy"], name="social_grou_is_acti_f88281_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="groupchallenge",
            index=models.Index(
                fields=["start_date", "end_date"], name="social_grou_start_d_6c8bcc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="challengeparticipant",
            index=models.Index(
                fields=["challenge", "score"], name="social_chal_challen_f597c2_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="challengeparticipant",
            unique_together={("challenge", "user")},
        ),
        migrations.AddIndex(
            model_name="socialfeeditem",
            index=models.Index(
                fields=["user", "created_at"], name="social_soci_user_id_71aab4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="socialfeeditem",
            index=models.Index(
                fields=["is_public", "created_at"], name="social_soci_is_publ_363949_idx"
            ),
        ),
    ]
