# Generated by Django 5.1.15 on 2026-05-30 12:01

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, max_length=1000)),
                ("color", models.CharField(default="#E8400C", max_length=7)),
                ("icon", models.CharField(blank=True, max_length=10)),
                (
                    "habit_type",
                    models.CharField(
                        choices=[
                            ("BINARY", "Binary (done / not done)"),
                            ("MEASURABLE", "Measurable (track a value)"),
                            ("TIME_BASED", "Time-based (track duration)"),
                        ],
                        default="BINARY",
                        max_length=20,
                    ),
                ),
                (
                    "target_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Target quantity e.g. 5 for '5 km'",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "target_unit",
                    models.CharField(
                        blank=True,
                        help_text="Unit label e.g. km, pages, minutes",
                        max_length=30,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("EASY", "Easy"),
                            ("MEDIUM", "Medium"),
                            ("HARD", "Hard"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                (
                    "frequency_type",
                    models.CharField(
                        choices=[
                            ("DAILY", "Every day"),
                            ("WEEKLY", "Specific days of the week"),
                            ("CUSTOM", "Custom interval"),
                        ],
                        default="DAILY",
                        max_length=10,
                    ),
                ),
                (
                    "frequency_days",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of weekday ints 0=Mon…6=Sun. Empty = every day.",
                    ),
                ),
                (
                    "frequency_interval",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="Every N days for CUSTOM frequency."
                    ),
                ),
                ("is_public", models.BooleanField(default=False)),
                ("is_archived", models.BooleanField(default=False)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="HabitCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                (
                    "icon",
                    models.CharField(blank=True, help_text="Emoji icon", max_length=10),
                ),
                (
                    "color",
                    models.CharField(
                        default="#E8400C", help_text="Hex color", max_length=7
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Display order"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "habit categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="HabitStreak",
            fields=[
                (
                    "habit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="streak",
                        serialize=False,
                        to="habits.habit",
                    ),
                ),
                ("current_streak", models.PositiveIntegerField(default=0)),
                ("longest_streak", models.PositiveIntegerField(default=0)),
                ("last_completion_date", models.DateField(blank=True, null=True)),
                ("streak_start_date", models.DateField(blank=True, null=True)),
                ("total_completions", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="habit",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="habits",
                to="habits.habitcategory",
            ),
        ),
        migrations.CreateModel(
            name="HabitCompletion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Measured value for MEASURABLE habits e.g. 5.2 km",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("note", models.TextField(blank=True, max_length=500)),
                (
                    "sentiment",
                    models.FloatField(
                        blank=True,
                        help_text="JournalAnalyzer sentiment score -1.0 to 1.0",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-1.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "verified_by",
                    models.CharField(
                        choices=[
                            ("USER", "Self-reported"),
                            ("AI_VISION", "AI photo verification"),
                            ("INTEGRATION", "Third-party integration"),
                        ],
                        default="USER",
                        max_length=20,
                    ),
                ),
                ("xp_earned", models.PositiveSmallIntegerField(default=0)),
                (
                    "habit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completions",
                        to="habits.habit",
                    ),
                ),
            ],
            options={
                "ordering": ["-completed_at"],
            },
        ),
        migrations.CreateModel(
            name="HabitReminder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("time", models.TimeField(help_text="Local time to send the reminder")),
                (
                    "days",
                    models.JSONField(
                        default=list,
                        help_text="Weekday ints 0=Mon…6=Sun. Empty = every day.",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "is_smart_timed",
                    models.BooleanField(
                        default=False,
                        help_text="If True, SmartScheduler overrides 'time' with ML-optimal timing",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "habit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="habits.habit",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="habit",
            index=models.Index(
                fields=["user", "is_archived", "deleted_at"],
                name="habits_habi_user_id_b6dd0b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="habit",
            index=models.Index(
                fields=["user", "created_at"], name="habits_habi_user_id_8aac28_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="habit",
            index=models.Index(
                fields=["is_public"], name="habits_habi_is_publ_af85bc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="habitcompletion",
            index=models.Index(
                fields=["habit", "completed_at"], name="habits_habi_habit_i_99b107_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="habitcompletion",
            index=models.Index(
                fields=["completed_at"], name="habits_habi_complet_62a799_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="habitcompletion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("completed_at__date", datetime.date(2026, 5, 30))),
                fields=("habit",),
                name="unique_completion_per_day",
            ),
        ),
    ]
