# Generated by Django 5.1.15 on 2026-06-01 05:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="habitcompletion",
            name="unique_completion_per_day",
        ),
        migrations.AddConstraint(
            model_name="habitcompletion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("completed_at__date", datetime.date(2026, 6, 1))),
                fields=("habit",),
                name="unique_completion_per_day",
            ),
        ),
    ]
