# Generated by Django 5.1.15 on 2026-06-01 05:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(max_length=500)),
                ("icon", models.CharField(help_text="Emoji icon", max_length=10)),
                ("color", models.CharField(default="#E8400C", max_length=7)),
                (
                    "condition_type",
                    models.CharField(
                        choices=[
                            ("STREAK_DAYS", "Reach a streak of N days"),
                            ("TOTAL_COMPLETIONS", "Complete habits N times total"),
                            ("HABITS_CREATED", "Create N habits"),
                            ("CHALLENGE_JOINED", "Join N challenges"),
                            ("CHALLENGE_WON", "Win N challenges"),
                            ("PERFECT_WEEK", "Complete all habits 7 days in a row"),
                            ("EARLY_BIRD", "Complete a habit before 7 AM N times"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "condition_value",
                    models.PositiveIntegerField(
                        help_text="The N in the condition e.g. streak of 7 days → 7"
                    ),
                ),
                ("xp_reward", models.PositiveIntegerField(default=100)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="XPLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("level", models.PositiveSmallIntegerField(unique=True)),
                ("xp_required", models.PositiveIntegerField()),
                (
                    "title",
                    models.CharField(help_text="e.g. Bronze, Silver, Gold, Diamond", max_length=50),
                ),
                ("icon", models.CharField(default="⭐", max_length=10)),
                ("color", models.CharField(default="#E8400C", max_length=7)),
            ],
            options={
                "ordering": ["level"],
            },
        ),
        migrations.CreateModel(
            name="Leaderboard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY", "Monthly"),
                            ("ALL_TIME", "All Time"),
                        ],
                        max_length=10,
                    ),
                ),
                ("started_at", models.DateField()),
                ("ended_at", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-started_at"],
                "unique_together": {("period", "started_at")},
            },
        ),
        migrations.CreateModel(
            name="UserXP",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="xp",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("total_xp", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "current_level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users_at_level",
                        to="gamification.xplevel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LeaderboardEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("rank", models.PositiveSmallIntegerField()),
                ("score", models.PositiveIntegerField(default=0)),
                ("completions", models.PositiveIntegerField(default=0)),
                (
                    "leaderboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="gamification.leaderboard",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaderboard_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["rank"],
                "unique_together": {("leaderboard", "user")},
            },
        ),
        migrations.CreateModel(
            name="UserBadge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("earned_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("notified", models.BooleanField(default=False)),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="earners",
                        to="gamification.badge",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-earned_at"],
                "unique_together": {("user", "badge")},
            },
        ),
    ]
