# Generated by Django 5.1.15 on 2026-06-01 05:31

from django.db import migrations

def seed_xp_levels(apps, schema_editor):
    XPLevel = apps.get_model("gamification", "XPLevel")

    levels = [
        (1,  0,      'Beginner',  '🌱', '#95A5A6'),
        (2,  500,    'Bronze',    '🥉', '#CD7F32'),
        (3,  1500,   'Silver',    '🥈', '#C0C0C0'),
        (4,  3500,   'Gold',      '🥇', '#FFD700'),
        (5,  7500,   'Platinum',  '💫', '#E8E8E8'),
        (6,  15000,  'Diamond',   '💎', '#56CCF2'),
        (7,  30000,  'Elite',     '⚡', '#9B51E0'),
        (8,  60000,  'Legend',    '🔥', '#E8400C'),
    ]

    for level, xp, title, icon, color in levels:
        XPLevel.objects.get_or_create(
            level=level,
            defaults={
                "xp_required": xp,
                "title": title,
                "icon": icon,
                "color": color,
            },
        )

class Migration(migrations.Migration):
    dependencies = [
        ("gamification", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_xp_levels),
    ]